### ISSUE TITLE
Conflict with Carpet mod (crash on startup)

### ISSUE THREAD

**Issue by InsaanNotFound** [lucaargolo/terrarian-slimes#1]
`[12:35:19] [main/WARN]: @Redirect conflict. Skipping terrarianslimes.mixins.json:PistonBlockMixin->@Redirect::redirectIsMovableBlockEntityCheck(Lnet/minecraft/class_2248;)Z with priority 200, already redirected by carpet.mixins.json:PistonBlock_movableTEMixin->@Redirect::ifHasBlockEntity(Lnet/minecraft/class_2248;)Z with priority 1000`

**Comment by lucaargolo** [comment]
That wasn't supposed to crash cause I had already lowered the redirect's priority, but apparently, you still need to tell the mixin injector that your mixin is not necessary, even if its priority is already lower than the one replacing it. TIL
This should be fixed in 1.0.1.
