### ISSUE TITLE
Crash on launch, on Fabric 1.19.2

### ISSUE THREAD

**Issue by TalEdd** [lucaargolo/terrarian-slimes#23]
[crash-2022-10-01_00.58.19-client.txt](https://github.com/lucaargolo/terrarian-slimes/files/9686402/crash-2022-10-01_00.58.19-client.txt)

**Comment by LunaticWyrm467** [comment]
Also can confirm this crash.

**Comment by kiddthejuice** [comment]
Came here to post this as well. My last crash report is below. I disabled it only and was able to boot up and run fine after.
[crash-2022-10-16_12.26.03-server.txt](https://github.com/lucaargolo/terrarian-slimes/files/9795379/crash-2022-10-16_12.26.03-server.txt)
