### ISSUE TITLE
Crash Upon Start

### ISSUE THREAD

**Issue by Blunder-G** [lucaargolo/terrarian-slimes#4]
Crash Upon Startup:

[crash-2021-05-27_22.28.48-client.txt](https://github.com/lucaargolo/terrarian-slimes/files/6556401/crash-2021-05-27_22.28.48-client.txt)

**Comment by lucaargolo** [comment]
Sorry for taking too long to answer, but this looks like a problem with outvoted. I took a look at their GitHub repo and seems like there was simillar issues happening with other mods. Try updating it and see if that fixes it. 
As this is not my fault i'll be closing this issue.
